---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - github.csye7125.team05
  resources:
  - githubreleasemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.csye7125.team05
  resources:
  - githubreleasemonitors/finalizers
  verbs:
  - update
- apiGroups:
  - github.csye7125.team05
  resources:
  - githubreleasemonitors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - github.csye7125.team05
  resources:
  - githubreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.csye7125.team05
  resources:
  - githubreleases/finalizers
  verbs:
  - update
- apiGroups:
  - github.csye7125.team05
  resources:
  - githubreleases/status
  verbs:
  - get
  - patch
  - update
